export const categories = [
  { id: 0, title: 'Category 0', tmb: 'tmb0.jpg' },
  { id: 1, title: 'Category 1', tmb: 'tmb1.jpg' },
  { id: 2, title: 'Category 2', tmb: 'tmb2.jpg' },
  { id: 3, title: 'Category 3', tmb: 'tmb3.jpg' },
  { id: 4, title: 'Category 4', tmb: 'tmb4.jpg' },
  { id: 5, title: 'Category 5', tmb: 'tmb5.jpg' },
  { id: 6, title: 'Category 6', tmb: 'tmb6.jpg' },
  { id: 7, title: 'Category 7', tmb: 'tmb7.jpg' },
  { id: 8, title: 'Category 8', tmb: 'tmb8.jpg' },
  { id: 9, title: 'Category 9', tmb: 'tmb9.jpg' },
];

export const subcategories = [
  {
    id: 0,
    title: 'SubCategory 0',
    tmb: 'tmb0.jpg',
    categoryId: 6,
  },
  {
    id: 1,
    title: 'SubCategory 1',
    tmb: 'tmb1.jpg',
    categoryId: 9,
  },
  {
    id: 2,
    title: 'SubCategory 2',
    tmb: 'tmb2.jpg',
    categoryId: 1,
  },
  {
    id: 3,
    title: 'SubCategory 3',
    tmb: 'tmb3.jpg',
    categoryId: 10,
  },
  {
    id: 4,
    title: 'SubCategory 4',
    tmb: 'tmb4.jpg',
    categoryId: 0,
  },
  {
    id: 5,
    title: 'SubCategory 5',
    tmb: 'tmb5.jpg',
    categoryId: 7,
  },
  {
    id: 6,
    title: 'SubCategory 6',
    tmb: 'tmb6.jpg',
    categoryId: 2,
  },
  {
    id: 7,
    title: 'SubCategory 7',
    tmb: 'tmb7.jpg',
    categoryId: 6,
  },
  {
    id: 8,
    title: 'SubCategory 8',
    tmb: 'tmb8.jpg',
    categoryId: 2,
  },
  {
    id: 9,
    title: 'SubCategory 9',
    tmb: 'tmb9.jpg',
    categoryId: 7,
  },
  {
    id: 10,
    title: 'SubCategory 10',
    tmb: 'tmb10.jpg',
    categoryId: 2,
  },
  {
    id: 11,
    title: 'SubCategory 11',
    tmb: 'tmb11.jpg',
    categoryId: 9,
  },
  {
    id: 12,
    title: 'SubCategory 12',
    tmb: 'tmb12.jpg',
    categoryId: 6,
  },
  {
    id: 13,
    title: 'SubCategory 13',
    tmb: 'tmb13.jpg',
    categoryId: 6,
  },
  {
    id: 14,
    title: 'SubCategory 14',
    tmb: 'tmb14.jpg',
    categoryId: 10,
  },
  {
    id: 15,
    title: 'SubCategory 15',
    tmb: 'tmb15.jpg',
    categoryId: 3,
  },
  {
    id: 16,
    title: 'SubCategory 16',
    tmb: 'tmb16.jpg',
    categoryId: 0,
  },
  {
    id: 17,
    title: 'SubCategory 17',
    tmb: 'tmb17.jpg',
    categoryId: 8,
  },
  {
    id: 18,
    title: 'SubCategory 18',
    tmb: 'tmb18.jpg',
    categoryId: 0,
  },
  {
    id: 19,
    title: 'SubCategory 19',
    tmb: 'tmb19.jpg',
    categoryId: 7,
  },
  {
    id: 20,
    title: 'SubCategory 20',
    tmb: 'tmb20.jpg',
    categoryId: 9,
  },
  {
    id: 21,
    title: 'SubCategory 21',
    tmb: 'tmb21.jpg',
    categoryId: 10,
  },
  {
    id: 22,
    title: 'SubCategory 22',
    tmb: 'tmb22.jpg',
    categoryId: 7,
  },
  {
    id: 23,
    title: 'SubCategory 23',
    tmb: 'tmb23.jpg',
    categoryId: 4,
  },
  {
    id: 24,
    title: 'SubCategory 24',
    tmb: 'tmb24.jpg',
    categoryId: 2,
  },
  {
    id: 25,
    title: 'SubCategory 25',
    tmb: 'tmb25.jpg',
    categoryId: 0,
  },
  {
    id: 26,
    title: 'SubCategory 26',
    tmb: 'tmb26.jpg',
    categoryId: 3,
  },
  {
    id: 27,
    title: 'SubCategory 27',
    tmb: 'tmb27.jpg',
    categoryId: 5,
  },
  {
    id: 28,
    title: 'SubCategory 28',
    tmb: 'tmb28.jpg',
    categoryId: 8,
  },
  {
    id: 29,
    title: 'SubCategory 29',
    tmb: 'tmb29.jpg',
    categoryId: 6,
  },
  {
    id: 30,
    title: 'SubCategory 30',
    tmb: 'tmb30.jpg',
    categoryId: 7,
  },
  {
    id: 31,
    title: 'SubCategory 31',
    tmb: 'tmb31.jpg',
    categoryId: 2,
  },
  {
    id: 32,
    title: 'SubCategory 32',
    tmb: 'tmb32.jpg',
    categoryId: 8,
  },
  {
    id: 33,
    title: 'SubCategory 33',
    tmb: 'tmb33.jpg',
    categoryId: 7,
  },
  {
    id: 34,
    title: 'SubCategory 34',
    tmb: 'tmb34.jpg',
    categoryId: 6,
  },
  {
    id: 35,
    title: 'SubCategory 35',
    tmb: 'tmb35.jpg',
    categoryId: 7,
  },
  {
    id: 36,
    title: 'SubCategory 36',
    tmb: 'tmb36.jpg',
    categoryId: 7,
  },
  {
    id: 37,
    title: 'SubCategory 37',
    tmb: 'tmb37.jpg',
    categoryId: 4,
  },
  {
    id: 38,
    title: 'SubCategory 38',
    tmb: 'tmb38.jpg',
    categoryId: 3,
  },
  {
    id: 39,
    title: 'SubCategory 39',
    tmb: 'tmb39.jpg',
    categoryId: 7,
  },
  {
    id: 40,
    title: 'SubCategory 40',
    tmb: 'tmb40.jpg',
    categoryId: 6,
  },
  {
    id: 41,
    title: 'SubCategory 41',
    tmb: 'tmb41.jpg',
    categoryId: 2,
  },
  {
    id: 42,
    title: 'SubCategory 42',
    tmb: 'tmb42.jpg',
    categoryId: 1,
  },
  {
    id: 43,
    title: 'SubCategory 43',
    tmb: 'tmb43.jpg',
    categoryId: 0,
  },
  {
    id: 44,
    title: 'SubCategory 44',
    tmb: 'tmb44.jpg',
    categoryId: 2,
  },
  {
    id: 45,
    title: 'SubCategory 45',
    tmb: 'tmb45.jpg',
    categoryId: 7,
  },
  {
    id: 46,
    title: 'SubCategory 46',
    tmb: 'tmb46.jpg',
    categoryId: 4,
  },
  {
    id: 47,
    title: 'SubCategory 47',
    tmb: 'tmb47.jpg',
    categoryId: 7,
  },
  {
    id: 48,
    title: 'SubCategory 48',
    tmb: 'tmb48.jpg',
    categoryId: 6,
  },
  {
    id: 49,
    title: 'SubCategory 49',
    tmb: 'tmb49.jpg',
    categoryId: 4,
  },
  {
    id: 50,
    title: 'SubCategory 50',
    tmb: 'tmb50.jpg',
    categoryId: 6,
  },
  {
    id: 51,
    title: 'SubCategory 51',
    tmb: 'tmb51.jpg',
    categoryId: 7,
  },
  {
    id: 52,
    title: 'SubCategory 52',
    tmb: 'tmb52.jpg',
    categoryId: 10,
  },
  {
    id: 53,
    title: 'SubCategory 53',
    tmb: 'tmb53.jpg',
    categoryId: 8,
  },
  {
    id: 54,
    title: 'SubCategory 54',
    tmb: 'tmb54.jpg',
    categoryId: 8,
  },
  {
    id: 55,
    title: 'SubCategory 55',
    tmb: 'tmb55.jpg',
    categoryId: 4,
  },
];
