import { ISubCategory } from '@/common/interfaces';

const subcategories :ISubCategory[] = [
  {
    id: 0,
    title: 'Play',
    image: 'img0.jpg',
    categoryId: 2,
  },
  {
    id: 1,
    title: 'Defense',
    image: 'img1.jpg',
    categoryId: 0,
  },
  {
    id: 2,
    title: 'Miss',
    image: 'img2.jpg',
    categoryId: 6,
  },
  {
    id: 3,
    title: 'Area',
    image: 'img3.jpg',
    categoryId: 4,
  },
  {
    id: 4,
    title: 'Full',
    image: 'img4.jpg',
    categoryId: 3,
  },
  {
    id: 5,
    title: 'Yourself',
    image: 'img5.jpg',
    categoryId: 2,
  },
  {
    id: 6,
    title: 'Manager',
    image: 'img6.jpg',
    categoryId: 1,
  },
  {
    id: 7,
    title: 'Way beyond',
    image: 'img7.jpg',
    categoryId: 1,
  },
  {
    id: 8,
    title: 'Born small',
    image: 'img8.jpg',
    categoryId: 4,
  },
  {
    id: 9,
    title: 'Still',
    image: 'img9.jpg',
    categoryId: 1,
  },
  {
    id: 10,
    title: 'Great bar',
    image: 'img10.jpg',
    categoryId: 3,
  },
  {
    id: 11,
    title: 'Seem',
    image: 'img11.jpg',
    categoryId: 6,
  },
  {
    id: 12,
    title: 'Sometimes short',
    image: 'img12.jpg',
    categoryId: 5,
  },
  {
    id: 13,
    title: 'Family',
    image: 'img13.jpg',
    categoryId: 3,
  },
  {
    id: 14,
    title: 'Computer',
    image: 'img14.jpg',
    categoryId: 6,
  },
  {
    id: 15,
    title: 'Herself',
    image: 'img15.jpg',
    categoryId: 3,
  },
  {
    id: 16,
    title: 'Unit measure',
    image: 'img16.jpg',
    categoryId: 5,
  },
  {
    id: 17,
    title: 'Everyone campaign',
    image: 'img17.jpg',
    categoryId: 4,
  },
  {
    id: 18,
    title: 'Away',
    image: 'img18.jpg',
    categoryId: 1,
  },
  {
    id: 19,
    title: 'Machine system',
    image: 'img19.jpg',
    categoryId: 5,
  },
  {
    id: 20,
    title: 'Foreign',
    image: 'img20.jpg',
    categoryId: 5,
  },
  {
    id: 21,
    title: 'Magazine',
    image: 'img21.jpg',
    categoryId: 4,
  },
  {
    id: 22,
    title: 'Investment',
    image: 'img22.jpg',
    categoryId: 6,
  },
  {
    id: 23,
    title: 'Table',
    image: 'img23.jpg',
    categoryId: 5,
  },
  {
    id: 24,
    title: 'Case',
    image: 'img24.jpg',
    categoryId: 3,
  },
  {
    id: 25,
    title: 'Value',
    image: 'img25.jpg',
    categoryId: 0,
  },
  {
    id: 26,
    title: 'In',
    image: 'img26.jpg',
    categoryId: 5,
  },
  {
    id: 27,
    title: 'Trade',
    image: 'img27.jpg',
    categoryId: 0,
  },
  {
    id: 28,
    title: 'Protect',
    image: 'img28.jpg',
    categoryId: 6,
  },
  {
    id: 29,
    title: 'Foreign',
    image: 'img29.jpg',
    categoryId: 5,
  },
  {
    id: 30,
    title: 'Name',
    image: 'img30.jpg',
    categoryId: 5,
  },
  {
    id: 31,
    title: 'And',
    image: 'img31.jpg',
    categoryId: 3,
  },
  {
    id: 32,
    title: 'Summer',
    image: 'img32.jpg',
    categoryId: 4,
  },
  {
    id: 33,
    title: 'Door president',
    image: 'img33.jpg',
    categoryId: 2,
  },
  {
    id: 34,
    title: 'Behavior',
    image: 'img34.jpg',
    categoryId: 0,
  },
  {
    id: 35,
    title: 'Generation people',
    image: 'img35.jpg',
    categoryId: 0,
  },
  {
    id: 36,
    title: 'Seat',
    image: 'img36.jpg',
    categoryId: 6,
  },
  {
    id: 37,
    title: 'Miss',
    image: 'img37.jpg',
    categoryId: 5,
  },
  {
    id: 38,
    title: 'Onto',
    image: 'img38.jpg',
    categoryId: 2,
  },
  {
    id: 39,
    title: 'Decide',
    image: 'img39.jpg',
    categoryId: 0,
  },
  {
    id: 40,
    title: 'Loss',
    image: 'img40.jpg',
    categoryId: 1,
  },
  {
    id: 41,
    title: 'Until',
    image: 'img41.jpg',
    categoryId: 6,
  },
  {
    id: 42,
    title: 'Power',
    image: 'img42.jpg',
    categoryId: 2,
  },
  {
    id: 43,
    title: 'Form pressure',
    image: 'img43.jpg',
    categoryId: 5,
  },
  {
    id: 44,
    title: 'Improve central',
    image: 'img44.jpg',
    categoryId: 5,
  },
  {
    id: 45,
    title: 'Necessary',
    image: 'img45.jpg',
    categoryId: 4,
  },
  {
    id: 46,
    title: 'Food',
    image: 'img46.jpg',
    categoryId: 2,
  },
  {
    id: 47,
    title: 'Central',
    image: 'img47.jpg',
    categoryId: 0,
  },
  {
    id: 48,
    title: 'Meeting',
    image: 'img48.jpg',
    categoryId: 4,
  },
  {
    id: 49,
    title: 'Everything measure',
    image: 'img49.jpg',
    categoryId: 0,
  },
  {
    id: 50,
    title: 'Sure',
    image: 'img50.jpg',
    categoryId: 0,
  },
  {
    id: 51,
    title: 'Magazine',
    image: 'img51.jpg',
    categoryId: 3,
  },
  {
    id: 52,
    title: 'Must',
    image: 'img52.jpg',
    categoryId: 4,
  },
  {
    id: 53,
    title: 'Win',
    image: 'img53.jpg',
    categoryId: 4,
  },
  {
    id: 54,
    title: 'Likely',
    image: 'img54.jpg',
    categoryId: 0,
  },
  {
    id: 55,
    title: 'Candidate',
    image: 'img55.jpg',
    categoryId: 2,
  },
  {
    id: 56,
    title: 'Not rather',
    image: 'img56.jpg',
    categoryId: 5,
  },
  {
    id: 57,
    title: 'Article party',
    image: 'img57.jpg',
    categoryId: 4,
  },
  {
    id: 58,
    title: 'Receive',
    image: 'img58.jpg',
    categoryId: 5,
  },
  {
    id: 59,
    title: 'Box mother',
    image: 'img59.jpg',
    categoryId: 5,
  },
  {
    id: 60,
    title: 'Room',
    image: 'img60.jpg',
    categoryId: 5,
  },
  {
    id: 61,
    title: 'Professional',
    image: 'img61.jpg',
    categoryId: 3,
  },
  {
    id: 62,
    title: 'More question',
    image: 'img62.jpg',
    categoryId: 3,
  },
  {
    id: 63,
    title: 'Human',
    image: 'img63.jpg',
    categoryId: 1,
  },
  {
    id: 64,
    title: 'Project',
    image: 'img64.jpg',
    categoryId: 1,
  },
  {
    id: 65,
    title: 'Leave',
    image: 'img65.jpg',
    categoryId: 3,
  },
  {
    id: 66,
    title: 'Use',
    image: 'img66.jpg',
    categoryId: 4,
  },
  {
    id: 67,
    title: 'Or',
    image: 'img67.jpg',
    categoryId: 5,
  },
  {
    id: 68,
    title: 'Because whose',
    image: 'img68.jpg',
    categoryId: 0,
  },
  {
    id: 69,
    title: 'President',
    image: 'img69.jpg',
    categoryId: 6,
  },
  {
    id: 70,
    title: 'Ready',
    image: 'img70.jpg',
    categoryId: 6,
  },
  {
    id: 71,
    title: 'Sit',
    image: 'img71.jpg',
    categoryId: 4,
  },
  {
    id: 72,
    title: 'Remember',
    image: 'img72.jpg',
    categoryId: 6,
  },
  {
    id: 73,
    title: 'Kind product',
    image: 'img73.jpg',
    categoryId: 2,
  },
  {
    id: 74,
    title: 'Yet',
    image: 'img74.jpg',
    categoryId: 6,
  },
  {
    id: 75,
    title: 'Contain',
    image: 'img75.jpg',
    categoryId: 0,
  },
  {
    id: 76,
    title: 'Art',
    image: 'img76.jpg',
    categoryId: 1,
  },
  {
    id: 77,
    title: 'Visit position',
    image: 'img77.jpg',
    categoryId: 5,
  },
  {
    id: 78,
    title: 'Moment',
    image: 'img78.jpg',
    categoryId: 3,
  },
  {
    id: 79,
    title: 'Staff',
    image: 'img79.jpg',
    categoryId: 0,
  },
  {
    id: 80,
    title: 'Level',
    image: 'img80.jpg',
    categoryId: 6,
  },
  {
    id: 81,
    title: 'Nation arm',
    image: 'img81.jpg',
    categoryId: 2,
  },
  {
    id: 82,
    title: 'Nor accept',
    image: 'img82.jpg',
    categoryId: 0,
  },
  {
    id: 83,
    title: 'Early',
    image: 'img83.jpg',
    categoryId: 5,
  },
  {
    id: 84,
    title: 'Not book',
    image: 'img84.jpg',
    categoryId: 4,
  },
  {
    id: 85,
    title: 'Weight',
    image: 'img85.jpg',
    categoryId: 1,
  },
  {
    id: 86,
    title: 'Group',
    image: 'img86.jpg',
    categoryId: 3,
  },
  {
    id: 87,
    title: 'Move',
    image: 'img87.jpg',
    categoryId: 5,
  },
  {
    id: 88,
    title: 'Upon',
    image: 'img88.jpg',
    categoryId: 1,
  },
  {
    id: 89,
    title: 'Community across',
    image: 'img89.jpg',
    categoryId: 4,
  },
];
export default subcategories;
