import { ISubCategory } from '@/common/interfaces';

const subcategories: ISubCategory[] = [
  {
    id: 0,
    title: 'Suggest',
    image: 'img0.jpg',
    categoryId: 6,
  },
  {
    id: 1,
    title: 'Most improve',
    image: 'img1.jpg',
    categoryId: 4,
  },
  {
    id: 2,
    title: 'From',
    image: 'img2.jpg',
    categoryId: 4,
  },
  {
    id: 3,
    title: 'Course',
    image: 'img3.jpg',
    categoryId: 2,
  },
  {
    id: 4,
    title: 'Education',
    image: 'img4.jpg',
    categoryId: 0,
  },
  {
    id: 5,
    title: 'Wall',
    image: 'img5.jpg',
    categoryId: 2,
  },
  {
    id: 6,
    title: 'Third',
    image: 'img6.jpg',
    categoryId: 2,
  },
  {
    id: 7,
    title: 'Stuff central',
    image: 'img7.jpg',
    categoryId: 5,
  },
  {
    id: 8,
    title: 'South',
    image: 'img8.jpg',
    categoryId: 3,
  },
  {
    id: 9,
    title: 'Note',
    image: 'img9.jpg',
    categoryId: 2,
  },
  {
    id: 10,
    title: 'Night hundred',
    image: 'img10.jpg',
    categoryId: 6,
  },
  {
    id: 11,
    title: 'Head',
    image: 'img11.jpg',
    categoryId: 6,
  },
  {
    id: 12,
    title: 'Meeting',
    image: 'img12.jpg',
    categoryId: 3,
  },
  {
    id: 13,
    title: 'True political',
    image: 'img13.jpg',
    categoryId: 4,
  },
  {
    id: 14,
    title: 'Many',
    image: 'img14.jpg',
    categoryId: 0,
  },
  {
    id: 15,
    title: 'Yet',
    image: 'img15.jpg',
    categoryId: 0,
  },
  {
    id: 16,
    title: 'Four',
    image: 'img16.jpg',
    categoryId: 6,
  },
  {
    id: 17,
    title: 'Interview',
    image: 'img17.jpg',
    categoryId: 0,
  },
  {
    id: 18,
    title: 'Already they',
    image: 'img18.jpg',
    categoryId: 6,
  },
  {
    id: 19,
    title: 'Kitchen',
    image: 'img19.jpg',
    categoryId: 3,
  },
  {
    id: 20,
    title: 'College',
    image: 'img20.jpg',
    categoryId: 1,
  },
  {
    id: 21,
    title: 'Ago employee',
    image: 'img21.jpg',
    categoryId: 3,
  },
  {
    id: 22,
    title: 'Home',
    image: 'img22.jpg',
    categoryId: 3,
  },
  {
    id: 23,
    title: 'Head',
    image: 'img23.jpg',
    categoryId: 2,
  },
  {
    id: 24,
    title: 'Too',
    image: 'img24.jpg',
    categoryId: 3,
  },
  {
    id: 25,
    title: 'Plan',
    image: 'img25.jpg',
    categoryId: 2,
  },
  {
    id: 26,
    title: 'Late',
    image: 'img26.jpg',
    categoryId: 2,
  },
  {
    id: 27,
    title: 'Government',
    image: 'img27.jpg',
    categoryId: 0,
  },
  {
    id: 28,
    title: 'Baby simply',
    image: 'img28.jpg',
    categoryId: 3,
  },
  {
    id: 29,
    title: 'Pattern',
    image: 'img29.jpg',
    categoryId: 3,
  },
  {
    id: 30,
    title: 'Though share',
    image: 'img30.jpg',
    categoryId: 5,
  },
  {
    id: 31,
    title: 'Beyond',
    image: 'img31.jpg',
    categoryId: 0,
  },
  {
    id: 32,
    title: 'Little individual',
    image: 'img32.jpg',
    categoryId: 5,
  },
  {
    id: 33,
    title: 'Produce',
    image: 'img33.jpg',
    categoryId: 6,
  },
  {
    id: 34,
    title: 'Must',
    image: 'img34.jpg',
    categoryId: 2,
  },
  {
    id: 35,
    title: 'Enough',
    image: 'img35.jpg',
    categoryId: 3,
  },
  {
    id: 36,
    title: 'Ground ever',
    image: 'img36.jpg',
    categoryId: 1,
  },
  {
    id: 37,
    title: 'Friend make',
    image: 'img37.jpg',
    categoryId: 1,
  },
  {
    id: 38,
    title: 'Wind',
    image: 'img38.jpg',
    categoryId: 3,
  },
  {
    id: 39,
    title: 'Paper',
    image: 'img39.jpg',
    categoryId: 4,
  },
  {
    id: 40,
    title: 'Hotel',
    image: 'img40.jpg',
    categoryId: 3,
  },
  {
    id: 41,
    title: 'Real',
    image: 'img41.jpg',
    categoryId: 6,
  },
  {
    id: 42,
    title: 'Imagine',
    image: 'img42.jpg',
    categoryId: 6,
  },
  {
    id: 43,
    title: 'Become build',
    image: 'img43.jpg',
    categoryId: 2,
  },
  {
    id: 44,
    title: 'Design',
    image: 'img44.jpg',
    categoryId: 6,
  },
  {
    id: 45,
    title: 'Especially',
    image: 'img45.jpg',
    categoryId: 5,
  },
  {
    id: 46,
    title: 'Try',
    image: 'img46.jpg',
    categoryId: 3,
  },
  {
    id: 47,
    title: 'Training',
    image: 'img47.jpg',
    categoryId: 1,
  },
  {
    id: 48,
    title: 'Every',
    image: 'img48.jpg',
    categoryId: 2,
  },
  {
    id: 49,
    title: 'Ok',
    image: 'img49.jpg',
    categoryId: 3,
  },
  {
    id: 50,
    title: 'Fall near',
    image: 'img50.jpg',
    categoryId: 0,
  },
  {
    id: 51,
    title: 'Learn',
    image: 'img51.jpg',
    categoryId: 4,
  },
  {
    id: 52,
    title: 'Message',
    image: 'img52.jpg',
    categoryId: 4,
  },
  {
    id: 53,
    title: 'Mention',
    image: 'img53.jpg',
    categoryId: 3,
  },
  {
    id: 54,
    title: 'Pull',
    image: 'img54.jpg',
    categoryId: 3,
  },
  {
    id: 55,
    title: 'For',
    image: 'img55.jpg',
    categoryId: 0,
  },
  {
    id: 56,
    title: 'Grow',
    image: 'img56.jpg',
    categoryId: 2,
  },
  {
    id: 57,
    title: 'Watch',
    image: 'img57.jpg',
    categoryId: 6,
  },
  {
    id: 58,
    title: 'Data',
    image: 'img58.jpg',
    categoryId: 2,
  },
  {
    id: 59,
    title: 'Site',
    image: 'img59.jpg',
    categoryId: 2,
  },
  {
    id: 60,
    title: 'Worry',
    image: 'img60.jpg',
    categoryId: 6,
  },
  {
    id: 61,
    title: 'After',
    image: 'img61.jpg',
    categoryId: 3,
  },
  {
    id: 62,
    title: 'Mean',
    image: 'img62.jpg',
    categoryId: 4,
  },
  {
    id: 63,
    title: 'Maybe toward',
    image: 'img63.jpg',
    categoryId: 2,
  },
  {
    id: 64,
    title: 'Miss',
    image: 'img64.jpg',
    categoryId: 4,
  },
  {
    id: 65,
    title: 'Attention the',
    image: 'img65.jpg',
    categoryId: 1,
  },
  {
    id: 66,
    title: 'Together next',
    image: 'img66.jpg',
    categoryId: 2,
  },
  {
    id: 67,
    title: 'Example hot',
    image: 'img67.jpg',
    categoryId: 5,
  },
  {
    id: 68,
    title: 'Expert attack',
    image: 'img68.jpg',
    categoryId: 1,
  },
  {
    id: 69,
    title: 'Some',
    image: 'img69.jpg',
    categoryId: 6,
  },
  {
    id: 70,
    title: 'Person choice',
    image: 'img70.jpg',
    categoryId: 4,
  },
  {
    id: 71,
    title: 'Design',
    image: 'img71.jpg',
    categoryId: 2,
  },
  {
    id: 72,
    title: 'Audience',
    image: 'img72.jpg',
    categoryId: 4,
  },
  {
    id: 73,
    title: 'Reality',
    image: 'img73.jpg',
    categoryId: 6,
  },
  {
    id: 74,
    title: 'Well read',
    image: 'img74.jpg',
    categoryId: 3,
  },
  {
    id: 75,
    title: 'Successful reach',
    image: 'img75.jpg',
    categoryId: 4,
  },
  {
    id: 76,
    title: 'Wrong',
    image: 'img76.jpg',
    categoryId: 4,
  },
  {
    id: 77,
    title: 'Common',
    image: 'img77.jpg',
    categoryId: 5,
  },
];

export default subcategories;
